sudo: required
services:
  - docker

before_install:
  - docker build -t vladimirkuchinskiy/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vladimirkuchinskiy/multi-client-test npm run ci-test

after_success:
  - docker build -t vladimirkuchinskiy/multi-client ./client
  - docker build -t vladimirkuchinskiy/multi-nginx ./nginx
  - docker build -t vladimirkuchinskiy/multi-server ./server
  - docker build -t vladimirkuchinskiy/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vladimirkuchinskiy/multi-client
  - docker push vladimirkuchinskiy/multi-nginx
  - docker push vladimirkuchinskiy/multi-server
  - docker push vladimirkuchinskiy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-446655339702
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
